config/routes.rb
Mispeliculas::Application.routes.draw do

  resources :peliculas
  
  root :to => redirect('/peliculas') 

end

app/models/pelicula.rb
class Pelicula < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  def index
    @peliculas = Pelicula.all
  end
  
  def show
      id = params[:id]
      @pelicula = Pelicula.find(id)
  end
  
  def new
  end
  
  def create
      @pelicula = Pelicula.create!(params[:pelicula])
      flash[:notice] = "#{@pelicula.titulo} se creo!"
      redirect_to peliculas_path
  end

  
  
  def edit
      @pelicula = Pelicula.find params[:id]
  end

  def update
      @pelicula = Pelicula.find params[:id]
      @pelicula.update_attributes!(params[:pelicula])
      flash[:notice] = "#{@pelicula.titulo} fue actualizada!!"
      redirect_to pelicula_path(@pelicula)
  end
  
  def destroy
      @pelicula = Pelicula.find params[:id]
      @pelicula.destroy
      flash[:notice] = "La pelicula #{@pelicula.titulo} fue destruida!!"
      redirect_to peliculas_path
  end

 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Mi Aplicacion en Rails Carlos Santamaria
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]

    =yield
    

app/views/peliculas/edit.html.haml
%h2 Nueva Película!
=form_tag pelicula_path(@pelicula), :method => :put do
  = label :pelicula, :titulo, 'Titulo'
  = text_field :pelicula, :titulo
  = label :pelicula, :calificacion, 'Calificacion'
  = select :pelicula, :calificacion, ['G', 'PG', 'PG-13', 'R', 'NC-17']
  = label :pelicula, :fecha_estreno, 'Estrenada en'
  = date_select :pelicula, :fecha_estreno
  %br
  = submit_tag 'Actualizar'

app/views/peliculas/index.html.haml
%h2 Listado de peliculas
%table#peliculas
  %thead
    %tr
      %th Titulo
      %th Calificacion
      %th Fecha Estreno
      %th Mas informacion
  %tbody
    - @peliculas.each do |pelicula|
      %tr
        %td= pelicula.titulo
        %td= pelicula.calificacion
        %td= pelicula.fecha_estreno
        %td= link_to "Mas sobre #{pelicula.titulo}", pelicula_path(pelicula)
        %td= link_to 'Agregar nueva pelicula' , new_pelicula_path

app/views/peliculas/new.html.haml
%h2 Nueva Película!
=form_tag peliculas_path, :method =>:post do
  = label :pelicula, :titulo, 'Titulo'
  = text_field :pelicula, :titulo
  = label :pelicula, :calificacion, 'Calificacion'
  = select :pelicula, :calificacion, ['G', 'PG', 'PG-13', 'R', 'NC-17']
  = label :pelicula, :fecha_estreno, 'Estrenada en'
  = date_select :pelicula, :fecha_estreno
  %br
  = submit_tag 'Guardar'

app/views/peliculas/show.html.haml
%h2 Detalles sobre #{@pelicula.titulo}

%ul#detalles
  %li
    Calificacion:
    = @pelicula.calificacion
  %li
    Estrenada el:
    = @pelicula.fecha_estreno.strftime("%B %d, %Y")

%h3 Descripcion:
%p#descripcion= @pelicula.descricion

= link_to 'Editar', edit_pelicula_path(@pelicula)

= link_to 'Regresar a la lista de peliculas', peliculas_path

= button_to 'Eliminar', pelicula_path(@pelicula), :method => :delete, :confirm => 'Estas seguro?'